version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: coursework
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis
    ports:
      - '6379:6379'
    celery:
      build: .
      tty: true
      command: celery -A config worker -l INFO
      depends_on:
        - redis
        - app

    celery_beat:
      build: .
      tty: true
      command: celery -A config beat -l info -S django
      depends_on:
        - redis
        - app